const express = require("express");
const app = express();
const cors = require("cors");
require("./server/config/mongoose.config");
const port = 8000;
app.use(cors());
app.use(express.json());
app.use(express.urlencoded({extended: true}));
require("./server/routes/authors.routes")(app);
app.listen(port, () => console.log(`Droppin eaves on port: ${port}`));